In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import BayesianRidge , LinearRegression
from sklearn.neural_network import MLPRegressor
from sklearn.datasets import make_regression
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from matplotlib import pyplot as plt

In [2]:
data = pd.read_csv('kg-okitsu.csv', sep = ";",decimal=',')

In [3]:
data

     ID_REGISTRO  ID_PARCELA     Area  Lluvia_Temporada       KG
0              1           1  3696.29             324.0  11130.0
1              2           2  1469.21             324.0   3216.0
2              3           3  1529.87             324.0      NaN
3              4           4  6247.46             324.0  24366.0
4              5           5  2763.91             324.0   3031.0
..           ...         ...      ...               ...      ...
310          311          59  3768.59             259.8   6653.0
311          312          60  2499.65             259.8  13249.0
312          313          61  1349.54             259.8   6937.0
313          314          62   531.84             259.8   1389.0
314          315          63  2478.04             259.8  11668.0

[315 rows x 5 columns]

In [4]:
data.dtypes

ID_REGISTRO           int64
ID_PARCELA            int64
Area                float64
Lluvia_Temporada    float64
KG                  float64
dtype: object

In [5]:
data.isnull().sum()

ID_REGISTRO          0
ID_PARCELA           0
Area                 0
Lluvia_Temporada     0
KG                  48
dtype: int64

In [6]:
data = data.dropna()

In [7]:
data.isnull().sum()

ID_REGISTRO         0
ID_PARCELA          0
Area                0
Lluvia_Temporada    0
KG                  0
dtype: int64

In [8]:
data

     ID_REGISTRO  ID_PARCELA     Area  Lluvia_Temporada       KG
0              1           1  3696.29             324.0  11130.0
1              2           2  1469.21             324.0   3216.0
3              4           4  6247.46             324.0  24366.0
4              5           5  2763.91             324.0   3031.0
5              6           6  2715.71             324.0   9512.0
..           ...         ...      ...               ...      ...
310          311          59  3768.59             259.8   6653.0
311          312          60  2499.65             259.8  13249.0
312          313          61  1349.54             259.8   6937.0
313          314          62   531.84             259.8   1389.0
314          315          63  2478.04             259.8  11668.0

[267 rows x 5 columns]

In [9]:
x = data[['Area', 'Lluvia_Temporada']]
scaler = StandardScaler()
x = scaler.fit_transform(x)

In [10]:
x

array([[ 0.77212701, -0.83451173],
       [-0.71885794, -0.83451173],
       [ 2.48008365, -0.83451173],
       [ 0.14791749, -0.83451173],
       [ 0.11564856, -0.83451173],
       [-0.83958522, -0.83451173],
       [ 2.20469316, -0.83451173],
       [-0.72275431, -0.83451173],
       [-1.02874003, -0.83451173],
       [ 0.19464717, -0.83451173],
       [-0.88075153, -0.83451173],
       [-0.06683153, -0.83451173],
       [-1.34418549, -0.83451173],
       [ 2.39273663, -0.83451173],
       [-0.38505534, -0.83451173],
       [-0.6971601 , -0.83451173],
       [-0.79897458, -0.83451173],
       [ 0.0616818 , -0.83451173],
       [ 0.67977228, -0.83451173],
       [-0.70550851, -0.83451173],
       [ 3.45979362, -0.83451173],
       [ 1.42248642, -0.83451173],
       [ 0.08949869, -0.83451173],
       [-0.09520408, -0.83451173],
       [-0.6626685 , -0.83451173],
       [ 1.43917655, -0.83451173],
       [-0.31439844, -0.83451173],
       [-0.46739465, -0.83451173],
       [-0.49298886, -0.83451173],
       [-0.78450712, -0.83451173],
       [-0.54528192, -0.83451173],
       [ 0.38269064, -0.83451173],
       [ 0.52399773, -0.83451173],
       [ 0.61301176, -0.83451173],
       [ 1.7462736 , -0.83451173],
       [ 0.51565602, -0.83451173],
       [-0.78284012, -0.83451173],
       [-1.07658105, -0.83451173],
       [-0.55863135, -0.83451173],
       [-0.54472626, -0.83451173],
       [-0.0501414 , -0.83451173],
       [-0.73777744, -0.83451173],
       [ 0.71927159, -0.83451173],
       [-0.49521153, -0.83451173],
       [-0.09186338, -0.83451173],
       [-1.03151837, -0.83451173],
       [ 0.10841818, -0.83451173],
       [ 0.90175168, -0.83451173],
       [-0.64320003, -0.83451173],
       [-0.02899923, -0.83451173],
       [ 0.77212701,  1.0887093 ],
       [-0.71885794,  1.0887093 ],
       [ 2.48008365,  1.0887093 ],
       [ 0.14791749,  1.0887093 ],
       [ 0.11564856,  1.0887093 ],
       [-0.83958522,  1.0887093 ],
       [ 2.20469316,  1.0887093 ],
       [-0.72275431,  1.0887093 ],
       [-1.02874003,  1.0887093 ],
       [ 0.19464717,  1.0887093 ],
       [-0.88075153,  1.0887093 ],
       [-0.06683153,  1.0887093 ],
       [-1.34418549,  1.0887093 ],
       [ 2.39273663,  1.0887093 ],
       [-0.38505534,  1.0887093 ],
       [-0.6971601 ,  1.0887093 ],
       [-0.79897458,  1.0887093 ],
       [ 0.0616818 ,  1.0887093 ],
       [ 0.67977228,  1.0887093 ],
       [-0.70550851,  1.0887093 ],
       [ 3.45979362,  1.0887093 ],
       [ 1.42248642,  1.0887093 ],
       [-0.09520408,  1.0887093 ],
       [-0.6626685 ,  1.0887093 ],
       [ 1.43917655,  1.0887093 ],
       [-0.31439844,  1.0887093 ],
       [ 0.59576596,  1.0887093 ],
       [-0.46739465,  1.0887093 ],
       [-0.49298886,  1.0887093 ],
       [-0.78450712,  1.0887093 ],
       [-0.54528192,  1.0887093 ],
       [ 0.38269064,  1.0887093 ],
       [ 0.52399773,  1.0887093 ],
       [ 0.42886466,  1.0887093 ],
       [-1.03708175,  1.0887093 ],
       [ 0.61301176,  1.0887093 ],
       [ 1.7462736 ,  1.0887093 ],
       [ 0.51565602,  1.0887093 ],
       [-0.78284012,  1.0887093 ],
       [-1.07658105,  1.0887093 ],
       [-0.55863135,  1.0887093 ],
       [-0.54472626,  1.0887093 ],
       [-0.0501414 ,  1.0887093 ],
       [-0.73777744,  1.0887093 ],
       [ 0.71927159,  1.0887093 ],
       [-0.55974938,  1.0887093 ],
       [-0.49521153,  1.0887093 ],
       [-0.09186338,  1.0887093 ],
       [-1.03151837,  1.0887093 ],
       [ 0.10841818,  1.0887093 ],
       [-0.44736382,  1.0887093 ],
       [ 0.90175168,  1.0887093 ],
       [-0.64320003,  1.0887093 ],
       [-0.55974938,  1.0887093 ],
       [ 0.8205304 ,  1.0887093 ],
       [-0.02899923,  1.0887093 ],
       [-0.79897458,  1.0887093 ],
       [-1.34640817,  1.0887093 ],
       [ 0.77212701, -0.21771229],
       [-0.71885794, -0.21771229],
       [ 2.48008365, -0.21771229],
       [ 0.14791749, -0.21771229],
       [ 0.11564856, -0.21771229],
       [-0.83958522, -0.21771229],
       [ 2.20469316, -0.21771229],
       [-0.72275431, -0.21771229],
       [-1.02874003, -0.21771229],
       [ 0.19464717, -0.21771229],
       [-0.88075153, -0.21771229],
       [-0.06683153, -0.21771229],
       [-1.34418549, -0.21771229],
       [-0.38505534, -0.21771229],
       [-0.6971601 , -0.21771229],
       [ 0.0616818 , -0.21771229],
       [ 0.67977228, -0.21771229],
       [-0.70550851, -0.21771229],
       [ 3.45979362, -0.21771229],
       [ 1.42248642, -0.21771229],
       [ 0.08949869, -0.21771229],
       [-0.09520408, -0.21771229],
       [-0.6626685 , -0.21771229],
       [ 1.43917655, -0.21771229],
       [-0.31439844, -0.21771229],
       [ 0.59576596, -0.21771229],
       [-0.46739465, -0.21771229],
       [-0.49298886, -0.21771229],
       [-0.78450712, -0.21771229],
       [-0.54528192, -0.21771229],
       [-1.20732375, -0.21771229],
       [ 0.38269064, -0.21771229],
       [ 0.52399773, -0.21771229],
       [ 0.42886466, -0.21771229],
       [-1.03708175, -0.21771229],
       [ 0.61301176, -0.21771229],
       [ 0.51565602, -0.21771229],
       [-0.78284012, -0.21771229],
       [-1.07658105, -0.21771229],
       [-0.55863135, -0.21771229],
       [-0.54472626, -0.21771229],
       [-0.0501414 , -0.21771229],
       [-0.73777744, -0.21771229],
       [ 0.71927159, -0.21771229],
       [-0.55974938, -0.21771229],
       [-0.49521153, -0.21771229],
       [-0.09186338, -0.21771229],
       [-1.03151837, -0.21771229],
       [ 0.10841818, -0.21771229],
       [ 0.90175168, -0.21771229],
       [-0.64320003, -0.21771229],
       [-0.55974938, -0.21771229],
       [ 0.8205304 , -0.21771229],
       [-0.02899923, -0.21771229],
       [-1.34640817, -0.21771229],
       [-0.04346669, -0.21771229],
       [ 0.77212701,  1.09748312],
       [ 2.48008365,  1.09748312],
       [ 0.14791749,  1.09748312],
       [ 0.11564856,  1.09748312],
       [-0.83958522,  1.09748312],
       [ 2.20469316,  1.09748312],
       [-1.02874003,  1.09748312],
       [ 0.19464717,  1.09748312],
       [-0.88075153,  1.09748312],
       [-0.06683153,  1.09748312],
       [-1.34418549,  1.09748312],
       [ 2.39273663,  1.09748312],
       [-0.38505534,  1.09748312],
       [-0.79897458,  1.09748312],
       [-0.70550851,  1.09748312],
       [ 3.45979362,  1.09748312],
       [ 1.42248642,  1.09748312],
       [ 0.08949869,  1.09748312],
       [-0.09520408,  1.09748312],
       [-0.6626685 ,  1.09748312],
       [ 1.43917655,  1.09748312],
       [-0.31439844,  1.09748312],
       [ 0.59576596,  1.09748312],
       [ 0.27809782,  1.09748312],
       [-0.46739465,  1.09748312],
       [-0.49298886,  1.09748312],
       [-0.78450712,  1.09748312],
       [-0.54528192,  1.09748312],
       [-1.20732375,  1.09748312],
       [ 0.38269064,  1.09748312],
       [ 0.52399773,  1.09748312],
       [ 0.42886466,  1.09748312],
       [-1.03708175,  1.09748312],
       [ 0.61301176,  1.09748312],
       [ 0.51565602,  1.09748312],
       [-0.78284012,  1.09748312],
       [-0.55863135,  1.09748312],
       [-0.54472626,  1.09748312],
       [-0.0501414 ,  1.09748312],
       [-0.73777744,  1.09748312],
       [ 0.71927159,  1.09748312],
       [-0.55974938,  1.09748312],
       [-0.49521153,  1.09748312],
       [-0.09186338,  1.09748312],
       [-1.03151837,  1.09748312],
       [ 0.10841818,  1.09748312],
       [ 0.90175168,  1.09748312],
       [-0.64320003,  1.09748312],
       [-0.55974938,  1.09748312],
       [ 0.8205304 ,  1.09748312],
       [-0.02899923,  1.09748312],
       [-0.79897458,  1.09748312],
       [-1.34640817,  1.09748312],
       [-0.04346669,  1.09748312],
       [ 0.77212701, -1.39779088],
       [ 2.48008365, -1.39779088],
       [-0.83958522, -1.39779088],
       [ 2.20469316, -1.39779088],
       [-1.02874003, -1.39779088],
       [ 0.19464717, -1.39779088],
       [-0.88075153, -1.39779088],
       [-0.06683153, -1.39779088],
       [-1.34418549, -1.39779088],
       [ 2.39273663, -1.39779088],
       [-0.38505534, -1.39779088],
       [-0.79897458, -1.39779088],
       [-0.70550851, -1.39779088],
       [ 3.45979362, -1.39779088],
       [ 0.08949869, -1.39779088],
       [-0.09520408, -1.39779088],
       [-0.6626685 , -1.39779088],
       [ 1.43917655, -1.39779088],
       [-0.31439844, -1.39779088],
       [ 0.59576596, -1.39779088],
       [ 0.27809782, -1.39779088],
       [-0.46739465, -1.39779088],
       [-0.49298886, -1.39779088],
       [-0.78450712, -1.39779088],
       [-0.54528192, -1.39779088],
       [-1.20732375, -1.39779088],
       [ 0.38269064, -1.39779088],
       [ 0.52399773, -1.39779088],
       [ 0.42886466, -1.39779088],
       [-1.03708175, -1.39779088],
       [ 0.51565602, -1.39779088],
       [-0.78284012, -1.39779088],
       [-0.55863135, -1.39779088],
       [-0.54472626, -1.39779088],
       [-0.73777744, -1.39779088],
       [ 0.71927159, -1.39779088],
       [-0.55974938, -1.39779088],
       [-0.49521153, -1.39779088],
       [-0.09186338, -1.39779088],
       [-1.03151837, -1.39779088],
       [ 0.10841818, -1.39779088],
       [ 0.90175168, -1.39779088],
       [-0.64320003, -1.39779088],
       [-0.55974938, -1.39779088],
       [ 0.8205304 , -1.39779088],
       [-0.02899923, -1.39779088],
       [-0.79897458, -1.39779088],
       [-1.34640817, -1.39779088],
       [-0.04346669, -1.39779088]])

In [11]:
y = data['KG']

In [12]:
y

0      11130.0
1       3216.0
3      24366.0
4       3031.0
5       9512.0
        ...
310     6653.0
311    13249.0
312     6937.0
313     1389.0
314    11668.0
Name: KG, Length: 267, dtype: float64

In [13]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [14]:
model=RandomForestRegressor(max_depth=6, random_state=0).fit(x_train,y_train)

In [15]:
model.score(x_test,y_test)

0.25120551379447054

In [16]:
x_train.size

426

In [17]:
y_pred = model.predict(x_test)

In [18]:
df = pd.DataFrame({'Actual': y_test, 'Prediccion': y_pred})

In [19]:
df

      Actual    Prediccion
211   5481.0  12595.664583
88    1938.0   3798.411405
248   2796.0   6748.709037
9     4130.0   4664.786131
309   5294.0   5615.950254
279   9804.0  10780.904534
113  11921.0   4152.828517
109   4386.0   9370.482507
234   5638.0   3527.075247
52    7625.0   4735.660353
296   7993.0   5839.285932
73    5804.0   5379.098350
184   5557.0   9026.532137
177  11489.0  10716.873883
242   7289.0   7562.222736
16    7503.0   5029.661223
169   2664.0   5114.763701
185   7434.0   9293.821705
175   5414.0   5472.281881
69     203.0   2579.959683
231   1799.0   2818.453008
239   8656.0   3547.097684
259  33540.0  18074.899853
8     3979.0   4435.560074
157   8773.0   7024.857999
145   2608.0  11953.763744
129   1727.0  29466.970859
294   1553.0   4453.193570
176   8617.0   6706.489172
289   2266.0   7379.232636
158   3100.0   4104.681164
276  13840.0  11569.739185
288  16619.0  15502.940556
118  15134.0  10793.463027
30    7654.0   6527.738705
126  14807.0  11019.040999
244  16258.0  10957.854111
43    7246.0   3841.192232
287   9553.0   8893.056283
21   35271.0  19673.025321
215  17170.0  24654.068762
261   6516.0   4549.923850
91    5212.0  10200.863985
307  11913.0  11714.014733
213  12808.0   8909.685373
6     4069.0   5659.969680
23    8922.0  11415.459567
221   3591.0   2379.206722
78    3093.0   3474.399383
13    5279.0   2837.181843
135   2854.0   4879.918251
233   8295.0   4092.593695
77   18543.0  14120.224843
277   6700.0   5452.079278